## Stage 1: Build Next.js app
# Expects these files to exist in the build context (prepared by CI):
#   website/public/pmtiles/communes.pmtiles      ← generated by build_pmtiles.py
#   data/exploration/<DUCKDB_FILE>               ← downloaded from S3 (default: dev.duckdb)
#
# Override the database file with: --build-arg DUCKDB_FILE=dev-trimmed.duckdb
FROM node:22-slim AS builder

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY website/package*.json ./
RUN npm ci

COPY website/ ./

ARG DUCKDB_FILE=dev.duckdb
COPY data/exploration/${DUCKDB_FILE} /data/database.duckdb

ENV DUCKDB_PATH=/data/database.duckdb

RUN npm run build


## Stage 2: Production runtime
FROM node:22-slim AS runner

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

WORKDIR /app
RUN chown nextjs:nodejs /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV DUCKDB_PATH=/data/database.duckdb
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV HOME=/app

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

RUN mkdir -p /data && chown nextjs:nodejs /data
COPY --from=builder --chown=nextjs:nodejs /data/database.duckdb /data/database.duckdb

USER nextjs

EXPOSE 3000
CMD ["node", "server.js"]
