name: upload-databases

on:
  push:
    branches:
      - main
    paths:
      - "data/dbt_pipeline/models/**"
  workflow_dispatch:

jobs:
  run-pipeline:
    name: Update DuckDB from S3-hosted csv files
    runs-on: ubuntu-latest

    env:
      CLEVER_S3_TOKEN: ${{ secrets.CLEVER_S3_TOKEN }}
      CLEVER_S3_SECRET: ${{ secrets.CLEVER_S3_SECRET }}
      CLEVER_REGION: ${{ vars.CLEVER_REGION }}
      CLEVER_ENDPOINT_URL: ${{ vars.CLEVER_ENDPOINT_URL }}
      CLEVER_PCC_BUCKET: ${{ vars.CLEVER_PCC_BUCKET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync

      - name: Set all files on S3 to public read
        run: |
          uv run python data/utils/set_all_files_to_public_read.py

      - name: Download pipeline csv inputs from bucket
        run: |
          uv run python data/utils/download_pipeline_inputs.py

      - name: Install dbt dependencies
        run: |
          cd data/dbt_pipeline
          uv run dbt deps

      - name: Run dbt (create dev.duckdb)
        run: |
          cd data/dbt_pipeline
          uv run dbt run

      - name: Upload dev.duckdb to bucket root
        run: |
          uv run python data/utils/duckdb_uploader.py
